package financialcrime

const (
	ALCOHOL_CONTRABAND                          = "Λαθρεμπόριο αλκοόλ"
	BRIBERY_AND_CORRUPTION_AGAINST_THE_STATE_EU = "Απιστία, δωροδοκία & διαφθορά σε βάρος Δημοσίου/ΕΕ"
	BY_PRODUCTS_OR_TRADEMARK_DISTRIBUTION       = "Διακίνηση προϊόντων παραεμπορίου ή Περί Σημάτων"
	CIGARETTE_CONTRABAND                        = "Λαθρεμπόριο τσιγάρων"
	COMMUNITY_AND_LOCAL_FUND_DISSEMINATION      = "Διασπάθιση κοινοτικών και εθνικών κονδυλίων"
	CORRUPTION                                  = "Διαφθορά"
	CRIMINAL_ACTS_BY_SA                         = "Αξιόποινες πράξεις από ΑΕ (100% μέτοχος το Δημόσιο)"
	CROSS_BORDER_ORGANIZED_CRIME                = "Διασυνοριακό οργανωμένο έγκλημα"
	EMBEZZLEMENT                                = "Υπεξαίρεση"
	FINANCIAL_OFFENSES_AGAINST_THE_STATE_EU     = "Οικονομικά αδικήματα εις βάρος Δημοσίου/ΕΕ"
	FINANCIAL_OFFENSES_AGAINST_THE_STATE_EU_V2  = "Οικονομικά αδικήματα σε βάρος Δημοσίου/Ε.Ε."
	FRAUD                                       = "Απάτες"
	FRAUD_AGAINST_INDIVIDUALS                   = "Απάτες σε βάρος ιδιωτών"
	FUEL_CONTRABAND                             = "Λαθρεμπόριο καυσίμων"
	FORGERY                                     = "Πλαστογραφία"
	GOODS_CONTRABAND                            = "Λαθρεμπόριο αγαθών"
	ILLEGAL_GAMBLING                            = "Παράνομος στοιχηματισμός - τυχερά παίγνια "
	ILLEGAL_GAMBLING_V2                         = "Παράνομος στοιχηματισμός τυχερών παιγνίων"
	ILLEGAL_TRAFFICKING_OF_COUNTERFEIT_GOODS    = "Παράνομη διακίνηση ή νόθευση αγαθών"
	INACCURATE_STATEMENT_OF_INCOME_ORIGINS      = "Ανακριβής δήλωση Πόθεν Έσχες"
	MONEY_LAUNDERING                            = "Νομιμοποίηση εσόδων από εγκληματικές δραστηριότητες"
	NGO_FINANCING                               = "Χρηματοδότηση Μ.Κ.Ο."
	OTHER_OFFENSES                              = "Λοιπά Αδικήματα ή Άλλα Π.Κ."
	SOCIAL_SECURITY_PROTECTION                  = "Προστασία κοινωνικής ασφάλισης"
	TAX_EVASION                                 = "Φοροδιαφυγή φυσικών και νομικών προσώπων"
	VIOLATION_OF_FREE_COMPETITION_MARKET_RULES  = "Παραβίαση κανόνων ελεύθερου ανταγωνισμού - αγοράς"
)
