package crime

const (
	MANSLAUGHTERS                     = "ΑΝΘΡΩΠΟΚΤΟΝΙΕΣ"
	FRAUDS                            = "ΑΠΑΤΕΣ"
	ANCIENT_ARTIFACT_THEFTS           = "ΑΡΧΑΙΟΚΑΠΗΛΕΙΑ"
	RAPES                             = "ΒΙΑΣΜΟΙ"
	EXTORTIONS                        = "ΕΚΒΙΑΣΕΙΣ"
	BEGGARY                           = "ΕΠΑΙΤΕΙΑ"
	ANIMAL_THEFTS                     = "ΖΩΟΚΛΟΠΗ"
	THEFTS_BURGLARIES_BY_PRIVATE_CARS = "Κλοπές - Διαρρήξεις από ιχε αυτ/τα"
	THEFTS_BURGLARIES_OF_HOLY_TEMPLES = "Κλοπές - Διαρρήξεις ιερών ναών"
	THEFTS_BURGLARIES_OF_STORES       = "Κλοπές - Διαρρήξεις καταστημάτων"
	THEFTS_BURGLARIES_OTHER           = "Κλοπές - Διαρρήξεις λοιπές"
	THEFTS_BURGLARIES_OF_HOMES        = "Κλοπές - Διαρρήξεις οικιών"
	THEFTS_BURGLARIES_IN_TRANSPORT    = "Κλοπές - Διαρρήξεις σε συγκοινωνιακά μέσα"
	THEFTS_OF_BAGS                    = "Κλοπές με αρπαγές τσαντών"
	THEFTS_IN_PUBLIC_SPACES           = "Κλοπές σε δημόσιο χώρο-μικροκλοπες"
	THEFTS_OF_PRIVATE_CARS            = "Κλοπές Τροχοφόρων ΙΧΕ αυτ/των"
	THEFTS_OF_PRIVATE_BUSES           = "Κλοπές Τροχοφόρων ΙΧΦ-Λεωφορείων"
	THEFTS_OF_OTHER_VEHICLES          = "Κλοπές Τροχοφόρων Λοιπών οχημάτων"
	THEFTS_OF_MOTOBICYCLES            = "Κλοπές Τροχοφόρων Μοτοποδηλάτων"
	THEFTS_OF_MOTORCYCLES             = "Κλοπές Τροχοφόρων Μοτοσυκλετών"
	COUNTERFEIT_NOTES                 = "ΚΥΚΛΟΦΟΡΙΑ ΠΑΡΑΧΑΡΑΓΜΕΝΩΝ"
	SNUGGLING                         = "ΛΑΘΡΕΜΠΟΡΙΟ"
	TAX_OFFICE_ROBBERIES              = "Ληστείες Δ.Ο.Υ."
	STORE_ROBBERIES                   = "Ληστείες εντός καταστημάτων"
	HOME_ROBBERIES                    = "Ληστείες εντός οικιών"
	PHONE_AND_SMALL_AMOUNT_ROBBERIES  = "Ληστείες κινητών τηλεφώνων-μικροποσών"
	OTHER_ROBBERIES                   = "Ληστείες λοιπές"
	BAG_SNATCHING_ROBBERIES           = "Ληστείες με αρπαγή τσάντας"
	TAXI_DRIVER_ROBBERIES             = "Ληστείες οδηγών ταξί"
	GAS_STATION_ROBBERIES             = "Ληστείες πρατηρίων υγρών καυσίμων"
	POST_OFFICE_ROBBERIES             = "Ληστείες σε ΕΛ.ΤΑ."
	MINI_MARKET_ROBBERIES             = "Ληστείες σε Μίνι Μάρκετ-κατ/τα ψιλικών"
	KIOSK_ROBBERIES                   = "Ληστείες σε περίπτερα"
	OPAP_AGENCY_ROBBERIES             = "Ληστείες σε πρακτορεία ΟΠΑΠ"
	SUPER_MARKET_ROBBERIES            = "Ληστείες σούπερ μάρκετ"
	COURIER_ROBBERIES                 = "Ληστείες ταχυδρομικών διανομέων"
	BANK_ROBBERIES                    = "Ληστείες τραπεζών"
	MONEY_SHIPPING_ROBBERIES          = "Ληστείες χρηματαποστολών"
	DRUGS                             = "Ν περί ΝΑΡΚΩΤΙΚΩΝ"
	GUNS                              = "Ν περί ΟΠΛΩΝ"
	INTELLECTUAL_PROPERTY             = "Ν περί ΠΝΕΥΜΑΤΙΚΗΣ ΙΔΙΟΚΤΗΣΙΑΣ"
	FORGERY                           = "ΠΛΑΣΤΟΓΡΑΦΙΑ"
	SEXUAL_EXPLOITATION               = "ΣΕΞΟΥΑΛΙΚΗ ΕΚΜΕΤΑΛΛΕΥΣΗ"
)
