package trafficviolations

const (
	ILLEGAL_PARKING                                 = " ΠΑΡΑΝΟΜΕΣ ΣΤΑΘΜΕΥΣΕΙΣ"
	UNINSURED_VEHICLES                              = "ΑΝΑΣΦΑΛΙΣΤΑ ΟΧΗΜΑΤΑ"
	ILLEGAL_USE_OF_LIGHTS                           = "ΑΝΤΙΚΑΝΟΝΙΚΗ ΧΡΗΣΗ ΦΩΤΩΝ"
	ILLEGAL_OVERTAKING                              = "ΑΝΤΙΚΑΝΟΝΙΚΟ ΠΡΟΣΠΕΡΑΣΜΑ"
	ILLEGAL_MANEUVERS                               = "ΑΝΤΙΚΑΝΟΝΙΚΟΙ ΕΛΙΓΜΟΙ"
	DRIVER_DISTRACTION                              = "ΑΠΟΣΠΑΣΗ ΠΡΟΣΟΧΗΣ ΟΔΗΓΟΥ"
	BILLBOARDS                                      = "ΔΙΑΦΗΜΙΣΤΙΚΕΣ ΠΙΝΑΚΙΔΕΣ"
	LACK_OF_SEAT_BELT                               = "ΕΛΛΕΙΨΗ ΖΩΝΗΣ ΑΣΦΑΛΕΙΑΣ "
	LACK_OF_LIGHTS                                  = "ΕΛΛΕΙΨΗ ΦΩΤΩΝ "
	NOISE_VIOLATION                                 = "ΘΟΡΥΒΟΙ ΓΕΝΙΚΑ"
	FUMES_VIOLATION                                 = "ΚΑΥΣΑΕΡΙΑ "
	OPPOSITE_MOVEMENT_IN_ONE_WAY_ROAD               = "ΚΙΝΗΣΗ ΑΝΤΙΘΕΤΗ ΣΕ ΜΟΝΟΔΡΟΜΟ"
	OPPOSITE_MOVEMENT_IN_TWO_WAY_ROAD               = "ΚΙΝΗΣΗ ΣΕ ΑΝΤΙΘΕΤΟ ΡΕΥΜΑ ΚΥΚΛΟΦΟΡΙΑΣ"
	DRIVING_ON_THE_LEFT_LANE                        = "ΚΙΝΗΣΗ ΣΤΗΝ ΑΡΙΣΤΕΡΗ ΛΩΡΙΔΑ"
	OTHER_ROAD_SIGN_VIOLATIONS                      = "ΛΟΙΠΕΣ ΠΑΡΑΒΑΣΕΙΣ ΣΗΜΑΝΣ. ΓΕΝΙΚΑ"
	NOT_DRIVING_ON_THE_RIGHT_LANE                   = "ΜΗ ΚΙΝΗΣΗ ΣΕ ΔΕΞΙΟ ΑΚΡΟ ΟΔΟΥ"
	SAFETY_DISTANCE_VIOLATION                       = "ΜΗ ΤΗΡΗΣΗ ΑΠΟΣΤΑΣΗΣ ΑΣΦΑΛΕΙΑΣ"
	SEAT_BELT_VIOLATION                             = "ΜΗ ΧΡΗΣΗ ΖΩΝΗΣ ΑΣΦΑΛΕΙΑΣ"
	CHILD_SEAT_VIOLATION                            = "ΜΗ ΧΡΗΣΗ ΠΑΙΔΙΚΩΝ ΚΑΘΙΣΜΑΤΩΝ"
	PROTECTIVE_HELMET_VIOLATION                     = "ΜΗ ΧΡΗΣΗ ΠΡΟΣΤΑΤΕΥΤΙΚΟΥ ΚΡΑΝΟΥΣ"
	DRIVING_UNDER_THE_INFLUENCE_OF_ALCOHOL_LOW      = "ΟΔΗΓΗΣΗ ΣΕ ΚΑΤΑΣΤΑΣΗ ΜΕΘΗΣ(0.10-0.24 mgr/l ή 0.20 - 0.49 gr/l)"
	DRIVING_UNDER_THE_INFLUENCE_OF_ALCOHOL_MID_LOW  = "ΟΔΗΓΗΣΗ ΣΕ ΚΑΤΑΣΤΑΣΗ ΜΕΘΗΣ(0.25-0.40 mgr/l ή 0.50 - 0.80 gr/l)"
	DRIVING_UNDER_THE_INFLUENCE_OF_ALCOHOL_HIGH_LOW = "ΟΔΗΓΗΣΗ ΣΕ ΚΑΤΑΣΤΑΣΗ ΜΕΘΗΣ(0.41-0.60 mgr/l ή 0.81 - 1.10 gr/l)"
	DRIVING_UNDER_THE_INFLUENCE_OF_ALCOHOL_HIGH     = "ΟΔΗΓΗΣΗ ΣΕ ΚΑΤΑΣΤΑΣΗ ΜΕΘΗΣ(>0.60mgr/l ή >1.10 gr/l)"
	CENTRE_OF_VEHICLE_TECHNICAL_CONTROL_VIOLATION   = "ΠΑΡΑΒΑΣΕΙΣ Κ.Τ.Ε.Ο."
	WORN_TIRE_VIOLATION                             = "ΠΑΡΑΒΑΣΕΙΣ ΦΘΑΡΜΕΝΩΝ ΕΛΑΣΤΙΚΩΝ"
	PEDESTRIAN_CROSSING_PRIORITY_VIOLATION          = "ΠΑΡΑΒΙΑΣΗ ΠΡΟΤΕΡ. ΠΕΖΩΝ ΣΕ ΔΙΑΒΑΣΗ"
	VEHICLE_PRIORITY_VIOLATION                      = "ΠΑΡΑΒΙΑΣΗ ΠΡΟΤΕΡΑΙΟΤΗΤΑΣ"
	TRAFFIC_LIGHT_VIOLATION                         = "ΠΑΡΑΒΙΑΣΗ ΣΗΜΑΤΟΔΟΤΗ"
	TRAFFIC_POLICEMAN_SIGN_VIOLATION                = "ΠΑΡΑΒΙΑΣΗ ΣΗΜΑΤΟΣ ΤΡΟΧΟΝΟΜΟΥ"
	DRIVING_LICENSE_SUSPENSION                      = "ΣΤΕΡΗΣΗ ΙΚΑΝΟΤΗΤΑΣ ΑΔΕΙΑΣ ΟΔΗΓΟΥ"
	OVERWEIGHT_OR_OVERSIZED_CARGO                   = "ΥΠΕΡΒΑΡΟ-ΔΙΑΣΤΑΣΕΙΣ ΦΟΡΤΙΟΥ "
	SPEEDING                                        = "ΥΠΕΡΒΟΛΙΚΗ ΤΑΧΥΤΗΤΑ "
	MOBILE_PHONE_USAGE                              = "ΧΡΗΣΗ ΚΙΝΗΤΟΥ ΤΗΛΕΦΩΝΟΥ"
)
