package electricityconsumption

const (
	CRETE            = "ΚΡΗΤΗ"
	RHODES           = "ΡΟΔΟΣ"
	LESVOS           = "ΛΕΣΒΟΣ"
	KOS_KALYMNOS     = "ΚΩΣ - ΚΑΛΥΜΝΟΣ"
	CHIOS            = "ΧΙΟΣ"
	SAMOS            = "ΣΑΜΟΣ"
	THIRA            = "ΘΗΡΑ"
	LEMNOS           = "ΛΗΜΝΟΣ"
	MILOS            = "ΜΗΛΟΣ"
	KARPATHOS        = "ΚΑΡΠΑΘΟΣ"
	IKARIA           = "ΙΚΑΡΙΑ"
	SIFNOS           = "ΣΙΦΝΟΣ"
	PATMOS           = "ΠΑΤΜΟΣ"
	SKIROS           = "ΣΚΥΡΟΣ"
	SYMI             = "ΣΥΜΗ"
	AMORGOS          = "ΑΜΟΡΓΟΣ"
	SERIFOS          = "ΣΕΡΙΦΟΣ"
	KYTHNOS          = "ΚΥΘΝΟΣ"
	ASTYPALAIA       = "ΑΣΤΥΠΑΛΑΙΑ"
	MEGISTI          = "ΜΕΓΙΣΤΗ"
	ANAFI            = "ΑΝΑΦΗ"
	AGIOS_EFSTRATIOS = "ΑΓ. ΕΥΣΤΡΑΤΙΟΣ"
	ERIKOYSSA        = "ΕΡΕΙΚΟΥΣΑ"
	OTHONI           = "ΟΘΩΝΟΙ"
	DONOUSSA         = "ΔΟΝΟΥΣΑ"
	AGATHONISSI      = "ΑΓΑΘΟΝΗΣΙ"
	GAVDOS           = "ΓΑΥΔΟΣ"
	ARKI             = "ΑΡΚΙΟΙ"
	ANTIKYTHIRA      = "ΑΝΤΙΚΥΘΗΡΑ"
)
