package academicprofessors

// Institutions.
const (
	NATIONAL_AND_KAPODISTRIAN_UNIVERSITY_OF_ATHENS = "ΕΘΝΙΚΟ & ΚΑΠΟΔΙΣΤΡΙΑΚΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΑΘΗΝΩΝ"
	ARISTOTLE_UNIVERSITY_OF_THESSALONIKI           = "ΑΡΙΣΤΟΤΕΛΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΕΣΣΑΛΟΝΙΚΗΣ"
	NATIONAL_TECHNICAL_UNIVERSITY_OF_ATHENS        = "ΕΘΝΙΚΟ ΜΕΤΣΟΒΙΟ ΠΟΛΥΤΕΧΝΕΙΟ"
	ATHENS_UNIVERSITY_OF_ECON_AND_BUSINESS         = "ΟΙΚΟΝΟΜΙΚΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΑΘΗΝΩΝ"
	AGRICULTURAL_UNIVERSITY_OF_ATHENS              = "ΓΕΩΠΟΝΙΚΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΑΘΗΝΩΝ"
	ATHENS_SCHOOL_OF_FINE_ARTS                     = "ΑΝΩΤΑΤΗ ΣΧΟΛΗ ΚΑΛΩΝ ΤΕΧΝΩΝ"
	PANTION_UNIVERSITY                             = "ΠΑΝΤΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΚΟΙΝΩΝΙΚΩΝ ΚΑΙ ΠΟΛΙΤΙΚΩΝ ΕΠΙΣΤΗΜΩΝ"
	UNIVERSITY_OF_PIRAEUS                          = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΠΕΙΡΑΙΩΣ"
	UNIVERSITY_OF_MACEDONIA                        = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΜΑΚΕΔΟΝΙΑΣ"
	UNIVERSITY_OF_PATRAS                           = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΠΑΤΡΩΝ"
	UNIVERSITY_OF_IOANNINA                         = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΙΩΑΝΝΙΝΩΝ"
	DEMOCRITUS_UNIVERSITY_OF_THRACE                = "ΔΗΜΟΚΡΙΤΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΡΑΚΗΣ"
	UNIVERSITY_OF_CRETE                            = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΚΡΗΤΗΣ"
	TECHNICAL_UNIVERSITY_OF_CRETE                  = "ΠΟΛΥΤΕΧΝΕΙΟ ΚΡΗΤΗΣ"
	AEGEAN_UNIVERSITY                              = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΑΙΓΑΙΟΥ"
	UNIVERSITY_OF_THESSALY                         = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΕΣΣΑΛΙΑΣ"
	IONIAN_UNIVERSITY                              = "ΙΟΝΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ"
	HAROKOPIO_UNIVERSITY                           = "ΧΑΡΟΚΟΠΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ"
	UNIVERSITY_OF_PELOPONNISSOS                    = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΠΕΛΟΠΟΝΝΗΣΟΥ"
	UNIVERSITY_OF_WEST_MACEDONIA                   = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ"
	UNIVERSITY_OF_WEST_ATTICA                      = "ΠΑΝΕΠΙΣΤΗΜΙΟ ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ"
	HELLENIC_OPEN_UNIVERSITY                       = "ΕΛΛΗΝΙΚΟ ΑΝΟΙΚΤΟ ΠΑΝΕΠΙΣΤΗΜΙΟ"
	INTERNATIONAL_UNIVERSITY_OF_GREECE             = "ΔΙΕΘΝΕΣ ΠΑΝΕΠΙΣΤΗΜΙΟ ΤΗΣ ΕΛΛΑΔΟΣ"
	GREEK_MEDITERRANEAN_UNIVERSITY                 = "ΕΛΛΗΝΙΚΟ ΜΕΣΟΓΕΙΑΚΟ ΠΑΝΕΠΙΣΤΗΜΙΟ"

	ASPETE = "ΑΣΠΑΙΤΕ"

	ECCLESIASTICAL_ACADEMY_OF_ATHENS            = "ΑΝΩΤΑΤΗ ΕΚΚΛΗΣΙΑΣΤΙΚΗ ΑΚΑΔΗΜΙΑ ΑΘΗΝΑΣ"
	ECCLESIASTICAL_ACADEMY_OF_THESSALONIKI      = "ΑΝΩΤΑΤΗ ΕΚΚΛΗΣΙΑΣΤΙΚΗ ΑΚΑΔΗΜΙΑ ΘΕΣΣΑΛΟΝΙΚΗΣ"
	ECCLESIASTICAL_ACADEMY_OF_IOANNINA          = "ΑΝΩΤΑΤΗ ΕΚΚΛΗΣΙΑΣΤΙΚΗ ΑΚΑΔΗΜΙΑ ΒΕΛΛΑΣ ΙΩΑΝΝΙΝΩΝ"
	PATRIARCHAL_ECCLESIASTICAL_ACADEMY_OF_CRETE = "ΠΑΤΡΙΑΡΧΙΚΗ ΑΝΩΤΑΤΗ ΕΚΚΛΗΣΙΑΣΤΙΚΗ ΑΚΑΔΗΜΙΑ ΚΡΗΤΗΣ"

	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_THESSALONIKI      = "ΑΛΕΞΑΝΔΡΕΙΟ ΤΕΙ ΘΕΣΣΑΛΟΝΙΚΗΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_CENTRAL_MACEDONIA = "ΤΕΙ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_WEST_MACEDONIA    = "ΤΕΙ ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_WEST_GREECE       = "ΤΕΙ ΔΥΤΙΚΗΣ ΕΛΛΑΔΑΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_THESSALY          = "ΤΕΙ ΘΕΣΣΑΛΙΑΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_CRETE             = "ΤΕΙ ΚΡΗΤΗΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_PELOPONNISSOS     = "ΤΕΙ ΠΕΛΟΠΟΝΝΗΣΟΥ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_STEREA_ELLADA     = "ΤΕΙ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_IPIROS            = "ΤΕΙ ΗΠΕΙΡΟΥ"
	TECHNOLOGICAL_EDUCATIONAL_INSTITUTE_OF_IONIAN_ISLANDS    = "ΤΕΙ ΙΟΝΙΩΝ ΝΗΣΩΝ"
)
