name: Go

on:
  push:
    branches: [ main ]
    paths-ignore: [ '*.md' 'LICENSE' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '*.md' 'LICENSE' ]
    
jobs:

  build:
    strategy:
      matrix:
        go: ['1.17.x', '1.16.x']
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        export DATAGOVGR_API_TOKEN=${{ secrets.DATAGOVGR_API_TOKEN }}
        go test ./...
